version: "3.7"

services:

  p21-data-loader:
    image: confluentinc/cp-kafkacat:7.0.1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "kafkacat -b kafka:19092 -K: -t p21-fhir -P -l /data/p21-data.ndjson"
    volumes:
      - ./p21-data.ndjson:/data/p21-data.ndjson:ro

  bar-data-loader:
    image: confluentinc/cp-kafkacat:7.0.1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "kafkacat -b kafka:19092 -K: -t bar-fhir -P -l /data/bar-data.ndjson"
    volumes:
      - ./bar-data.ndjson:/data/bar-data.ndjson:ro

  patient-data-loader:
    image: confluentinc/cp-kafkacat:7.0.1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "kafkacat -b kafka:19092 -K: -t patient-fhir -P -l /data/patient-data.ndjson"
    volumes:
      - ./patient-data.ndjson:/data/patient-data.ndjson:ro

  adt-data-loader:
    image: confluentinc/cp-kafkacat:7.0.1
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "kafkacat -b kafka:19092 -K: -t adt-fhir -P -l /data/adt-data.ndjson"
    volumes:
      - ./adt-data.ndjson:/data/adt-data.ndjson:ro
