spring:
  jmx:
    enabled: true
  kafka:
    input-topics:
    output-topic:
    consumer:
      properties:
        spring.json.use.type.headers: false
    producer:
      compression-type: gzip
      properties:
        max.request.size: 5242880
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: file://${SSL_TRUST_STORE_LOCATION_INTERNAL:/opt/kafka-streams-template/ssl/truststore.jks}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-location: file://${SSL_KEY_STORE_LOCATION_INTERNAL:/opt/kafka-streams-template/ssl/keystore.jks}
      key-store-password: ${SSL_KEY_STORE_PASSWORD}
    streams:
      replication-factor: 3
      application-id: fhir-merger

fhir:
  match-expression:

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.fhirmerger: debug
