merger:
  input:
    - topic: p21-fhir
      expression: Bundle.entry.where(resource.is(Condition) and resource.recordedDate <= @2021)
    - topic: bar-fhir-idat
      expression: Bundle.where((entry.resource.is(Condition) and entry.resource.recordedDate > @2021).exists())
  output.topic: test
